Naming/MethodParameterName:
  inherit_mode:
    override:
      - Include
  AllowedNames:
    - x
    - y
    - dx
    - dy

Metrics/ClassLength:
  Max: 1024

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 32